# PostgreSQL
# source: https://rubygems.org/gems/pg
#   gem install pg
#
#   Ensure the pg gem is defined in the Gemfile
#   gem "pg"
#


default: &default
  adapter: postgresql
  pool: 5 || <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  encoding: unicode
  username: postgres
  password: 12345678

development:
  <<: *default
  database: weather_app_dev

test:
  <<: *default
  database: weather_app_test


# Store production database in the storage/ directory, which by default
# is mounted as a persistent Docker volume in config/deploy.yml.
# production:
#   primary:
#     <<: *default
#     database: storage/production.sqlite3
#   cache:
#     <<: *default
#     database: storage/production_cache.sqlite3
#     migrations_paths: db/cache_migrate
#   queue:
#     <<: *default
#     database: storage/production_queue.sqlite3
#     migrations_paths: db/queue_migrate
#   cable:
#     <<: *default
#     database: storage/production_cable.sqlite3
#     migrations_paths: db/cable_migrate
